name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app image
        run: docker build -t demo-app:ci -f app/Dockerfile app

      - name: Run healthcheck
        run: |
          cid=$(docker run -d -p 8080:8080 demo-app:ci)
          sleep 2
          curl -f http://localhost:8080/health
          docker rm -f $cid